# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/python_functions',
                'doc_host': 'https://csi-hamburg.github.io',
                'git_url': 'https://github.com/csi-hamburg/python_functions',
                'lib_path': 'python_functions'},
  'syms': {'python_functions.core': {'python_functions.core.foo': ('core.html#foo', 'python_functions/core.py')}}}