# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/python_functions',
                'doc_host': 'https://csi-hamburg.github.io',
                'git_url': 'https://github.com/csi-hamburg/python_functions',
                'lib_path': 'python_functions'},
  'syms': { 'python_functions.core': {'python_functions.core.foo': ('core.html#foo', 'python_functions/core.py')},
            'python_functions.descriptive_statistics': { 'python_functions.descriptive_statistics.finalize_stats_2groups': ( 'descriptive_statistics.html#finalize_stats_2groups',
                                                                                                                             'python_functions/descriptive_statistics.py'),
                                                         'python_functions.descriptive_statistics.stats_2groups': ( 'descriptive_statistics.html#stats_2groups',
                                                                                                                    'python_functions/descriptive_statistics.py')},
            'python_functions.surface_contextualization': { 'python_functions.surface_contextualization.perform_spins': ( 'surface_contextualization.html#perform_spins',
                                                                                                                          'python_functions/surface_contextualization.py'),
                                                            'python_functions.surface_contextualization.plot_surface': ( 'surface_contextualization.html#plot_surface',
                                                                                                                         'python_functions/surface_contextualization.py'),
                                                            'python_functions.surface_contextualization.surface_to_schaefer': ( 'surface_contextualization.html#surface_to_schaefer',
                                                                                                                                'python_functions/surface_contextualization.py')}}}